### ISSUE TITLE
Server startup broken since 1.0.28

### ISSUE THREAD

**Issue by bart-d** [blocktronics/moebius#178]
Server startup is broken since version 1.0.28
```
# node ./server.js      
/srv/tmp/moebius/app/senders.js:3
const win = electron.remote.getCurrentWindow();
                            ^

TypeError: Cannot read property 'getCurrentWindow' of undefined
    at Object.<anonymous> (/srv/tmp/moebius/app/senders.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/srv/tmp/moebius/app/libtextmode/textmode.js:1:41)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)```

**Comment by bart-d** [comment]
https://github.com/blocktronics/moebius/commit/67192019234ecee019f39de2cd978ac36b2182ce#r46029721
